name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install boto3 gitpython

      - name: Clone repository
        run: |
          git clone https://github.com/davidkapcsandi/test1.git ${{ runner.workspace }}/repo

      - name: Run Python scripts
        run: |
          cd ${{ runner.workspace }}/repo
          python3 clone_repo.py
          python3 make_commit.py
          python3 deploy_aws_resources.py

